src/detector.change-attrs.test.ts
src/detector.clicks-resolved-bid.test.ts
src/detector.clicks-select-child.test.ts
src/detector.clicks.test.ts
src/detector.dynamic.test.ts
src/detector.impressions.test.ts
src/detector.purchases.test.ts
src/detector.ts
src/events.ts

The library cannot communicate with the Topsort backend because it's sending the incorrect event types in the events payload.
- `impressions` ->  `Impressions`
- `click` -> `ClickEvent`
- `purchase` -> `Purchase`
Reported by @twolfvb

Change event types to the ones specified in the API

---

@types/global.d.ts
src/detector.ts

In the context of Shopify we may end up loading the file multiple times, so in order to prevent the events being reported multime times, we add a check to the library to ensure the library is loaded only once per page.

feat: allow multiple loads

---

README.md

This should be `api.topsort.com` for most people anyway.

chore(docs): change default example URL

---

src/detector.ids.test.ts
src/detector.ts

The `getUserId()` function, when run for the first time, tries to fetch the user id from a cookie, but the current regex is not getting it correctly. This causes the user id to be reset every time the library loads

fix(userId): Prevent the id from resetting on every page refresh

---

CHANGELOG.md
mocks/api-server.ts
src/detector.ts
src/events.ts
src/reporter.test.ts
src/reporter.ts
tests/browser-test.ts

Use API V2 instead of V1, as this API removes uses of unnecessary fields and also allow to send multiple events in one batch. Note that this is not currently done in this PR and will be an improvement for the future.

feat: migrate to API v2

---

README.md

Mention how to treat JSON data inside `ts-data-items`

chore(docs): improve documentation about purchases

---

README.md
mocks/api-server.ts
src/detector.ts
src/events.ts
src/store.ts
tests/browser-test.ts
tests/test.html

In case customers want to attribute purchases to banners they need to specify a product and a resolved bid as inherit. In such a case we would grab the resolved id id that was stored in session storage in the previous click.
There are some caveats with this approach:
1) If there's a mistake and an inherit resolved bid is used in a page which is not the target of a banner, then the events will fail. 2) It could happen that the user manually changes the url to a banner's destination page and in that case we would report the events to the wrong banner. 3) This won't always work if session storage is not available (support is 97.4% https://caniuse.com/mdn-api_window_sessionstorage). We have a fallback using an in memory cache, but that would only work if the page it's not reloaded (Vue, …

feat: propagate additional products

---

package.json

The library is pure js so it shouldn't matter the version of node.

chore: remove engine from packageJson

---

src/detector.ts

Switch from `location.pathname` to also include `location.search` as part of passing path belonging to events.

feat: add `location.search` to default event path

---

package.json
pnpm-lock.yaml
tsconfig.json

We bump vite and vitest to their latest versions. Note that I had to change the TS `moduleResolution` to `bundler`, but that should not generate any issues as we are using that config only for checking the types.
Closes: https://github.com/Topsort/analytics.js/pull/245
Closes: https://github.com/Topsort/analytics.js/pull/248

chore(deps-dev): bump vite and vitest

---

package.json
pnpm-lock.yaml
src/reporter.test.ts

Version 2 of msw saw significant [breaking changes](https://github.com/mswjs/msw/releases/tag/v2.0.0). We resolved them mostly by running the codemod `npx codemod msw/2/upgrade-recipe`, but then we had to adjust the [netowrk error](https://mswjs.io/docs/migrations/1.x-to-2.x#resnetworkerror) and the base path of the request.

chore(deps): bump msw to v2.3.0

---

README.md
src/queue.ts

Share learnings from working with `require.js` which is used in certain Magento setups.

chore(docs): add a troubleshooting section

---

CHANGELOG.md
src/detector.ts
src/set.test.ts
src/set.ts

The logic to truncate a set was incorrect and could produce and almost inifinite loop as it was decreasing the counter rather than increasing it. We extracted the logic to its own module, where it can be tested.

fix: correctly truncate seenEvents

---

CHANGELOG.md
src/detector.purchases.test.ts
src/detector.ts

The id we were generating for purshases was alays the same as purchases do not have a bid id, meaning that if two purchases were reported in the same page, only one of them was being reported.

fix: use items in purchase ids

---

package.json
pnpm-lock.yaml
src/detector.ts

This PR bumps the version of `@topsort/sdk` from 0.2.0 to 0.3.1
| File | Before (gzip) | After (gzip) |
|:-------|:-------|:-------|
| dist/ts.mjs | 10.77 kB (3.76 kB) | 11.15 kB (3.91 kB) |
| dist/ts.js | 7.93 kB (3.33 kB) |  8.17 kB (3.46 kB) |
The difference comes from:
- Now the [TopsortClient](https://github.com/Topsort/topsort.js/blob/main/src/functions/topsort-client.ts#L8) class handles the function calls after receiving the config;
- The APIClient now handles the [URL sanitization](https://github.com/Topsort/topsort.js/blob/main/src/lib/api-client.ts#L57);
- We have improved the [error handling and response](https://github.com/Topsort/topsort.js/blob/main/src/lib/api-client.ts#L10), as most of our calls return status code 204 (No Content). Therefore, we wouldn't need to parse any …

chore(deps): @topsort/sdk v0.3.1

---

.github/workflows/checkpr.yml
.github/workflows/publish-to-npm.yml
package.json

According to `actions/node-setup`, it will read `manifest.engine` values to decide what node version to use.
Second, the lockfile path is only relevant if it is non-default.
Refs: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file

chore: replace environment variables with `package.json` entries

---

README.md
src/detector.purchases.test.ts
src/detector.ts

Support recieving vendorId in purchases since this is what we generally recommend as part of an integration.

feat: support `vendorId` in purchase events

---

README.md
src/detector.custom-getuserid.test.ts
src/detector.ts

This is useful when you want to handle your own logic for what you want to pass as `opaqueUserId`.

feat: support passing custom getUserId function

---

README.md

Updated installation to remove unpkg script tags and use a local file or bundler.

fix: README.md update installation without unpkg script tags

---

package.json

Required for OIDC publish workflows. Should've probably have been in there either way.

fix: add repository url to `package.json`
